# Generated by Django 3.1.1 on 2020-10-21 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectid', models.AutoField(primary_key=True, serialize=False)),
                ('projectname', models.CharField(max_length=250)),
                ('projectowner', models.CharField(max_length=50)),
                ('repositoryurl', models.CharField(max_length=250)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_service.product')),
            ],
        ),
    ]
