# Generated by Django 3.1.1 on 2020-10-23 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_service', '0003_auto_20201021_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('pipelineid', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=250)),
                ('commitid', models.IntegerField(help_text='Github commit id')),
                ('jobid', models.IntegerField(help_text='Jenkins Build Id')),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Time in Seconds')),
                ('result', models.CharField(max_length=10)),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_service.project')),
            ],
        ),
    ]
