# Generated by Django 3.1.1 on 2020-10-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_service', '0004_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='duration',
            field=models.IntegerField(help_text='Time in Seconds', null=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='endtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='result',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
