# Generated by Django 3.1.1 on 2020-10-25 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_service', '0005_auto_20201023_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totaltestcase', models.IntegerField()),
                ('testcasepassed', models.IntegerField()),
                ('testcasefailed', models.IntegerField()),
                ('testcaseskipped', models.IntegerField()),
                ('passpercent', models.IntegerField()),
                ('pipelineid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_service.pipeline')),
            ],
        ),
    ]
