# Generated by Django 3.1.1 on 2020-10-25 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_service', '0006_testreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('testsuiteid', models.AutoField(primary_key=True, serialize=False)),
                ('testsuitename', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('testid', models.AutoField(primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField()),
                ('testcasename', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Time in Seconds')),
                ('result', models.CharField(max_length=10)),
                ('pipelineid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_service.pipeline')),
                ('testsuiteid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_service.testsuite')),
            ],
        ),
    ]
