# Generated by Django 3.1.1 on 2020-10-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_service', '0007_testcase_testsuite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='duration',
            field=models.IntegerField(help_text='Time in Seconds', null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='result',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='owner',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
